### PR TITLE
Uploading Version 2 of Python Project

### PR DESCRIPTION
**Pull request by dpaul1993**
Hello Professor,

We have reflected the recommended modifications, as said, in our Python Project. These amendments have bolstered machine learning model efficiency to a great extent. Kindly review our project and let us know if anything further needed to be implemented or performed.

Thanks and Regards,
Debayan Paul

### CODE REVIEW

**Comment by bnajafi** [comment]
Thank you for your update, 
There is a minor modification which is still needed to be applied.Pay attention that, since your data is measured each 15 minutes, once you are lagging the parameters, you should start lagging after number 4 (which means 1 hour (4*15)) or alternatively add all the lags and then remove the first three lagged values. The latter is due to the fact that you are predicting an hour ahead and you should not include any information provided less than an hour before your prediction.

**Comment by dpaul1993** [comment]
Hello Professor,

Thanking for replying back. As you have mentioned, I have already done this lagging modification accordingly in both of the previous versions. As you can see, as our dataset is measured every 15 minutes and we are trying to lag by 1 hour which means four rows (4*15 min), I have shifted the row 4 times at a once by using "shift(i*4)" in the function. Nonetheless, I have still checked that part and saw that part was up and running accordingly. I have attached a pdf file which contains the appropriate screenshots of that part which I used to verify. Kindly review that once, and let me know if this part is functioning correctly or not. If still some issues remain unresolved, kindly let me know if we could discuss this once for a few minutes of your time on 01.02.2018.

Anticipating for your precious feedback.

Thanks and Regards,
Debayan Paul
[project.pdf](https://github.com/bnajafi/Data-driven_Building_Simulation_Projects/files/1670638/project.pdf)

**Comment by dpaul1993** [comment]
Hello Professor,

Thanking for replying back. As you have mentioned, I have already done this
lagging modification accordingly in both of the previous versions. As you
can see, as our dataset is measured every 15 minutes and we are trying to
lag by 1 hour which means four rows (4*15 min), I have shifted the row 4
times at a once by using "shift(i*4)" in the function. Nonetheless, I have
still checked that part and saw that part was up and running accordingly. I
have attached a pdf file which contains the appropriate screenshots of that
part which I used to verify. Kindly review that once, and let me know if
this part is functioning correctly or not. If still some issues remain
unresolved, kindly let me know if we could discuss this once for a few
minutes of your time on 01.02.2018.

Anticipating for your precious feedback.

Thanks and Regards,
Debayan Paul

**Comment by bnajafi** [comment]
Dear Debyan,

yes, as I have already converted them into hourly value, the problem is resolved, I should have mixed it with a similar project. Sure, we can discuss about it.

**Pull request merged**
